spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:mysql://localhost/bd_users?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    discovery:
      enabled: true
    config:
      enabled: false
server:
  port: 8089
springdoc:
  override-with-generic-response: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

