spring:
  application:
    name: "event-service"
  datasource:
    url: jdbc:mysql://localhost:3306/eventsdb
    # Uncomment and adjust the following line if using the local MySQL server
    # url: jdbc:mysql://host.docker.internal:3306/bd_event?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: my-secret
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false

server:
  port: 8085

springdoc:
  override-with-generic-response: false
