spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:mysql://localhost/bd_ticket?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

springdoc:
  override-with-generic-response: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true